print ('-' * 35)
print ('Tugas1 Sisop Kelas A')
print ('-' * 35)
print ('Nama = Galang Surya Ramadhan')
print ('Npm = 21083010081')
print ('-' * 35)
print ('notes: ')
print ('-' * 35)
print ('Halo Gaissssss!!!!!!!!!!!!')
print ('ini adalah skrip bash pertamaku di Linux')
